# Generated by Django 2.2.4 on 2019-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.TextField(choices=[('1', 'urgent'), ('2', 'average'), ('3', 'flexible')], default='average'),
        ),
    ]
